import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Diátaxis: four parallel sidebars, one per category.
// Source of truth for the tree: ../sms-app/docs/docs-site-build/03-content-architecture.md

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  howtoSidebar: [{ type: 'autogenerated', dirName: 'how-to' }],
  referenceSidebar: [{ type: 'autogenerated', dirName: 'reference' }],
  explanationSidebar: [{ type: 'autogenerated', dirName: 'explanation' }],
};

export default sidebars;
